export const EVENT_STATUS = {
  DRAFT: "DRAFT",
  SCHEDULED: "SCHEDULED",
  ONGOING: "ONGOING",
  DONE: "DONE",
  CANCELED: "CANCELED",
} as const;

export const EVENT_FORMAT = {
  ONLINE: "ONLINE",
  OFFLINE: "OFFLINE",
  HYBRID: "HYBRID",
};
